---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: root
  vars:
      clickhouse_tcp_port: 9000
      clickhouse_dbs_custom:
        - { name: logs }
  roles:
      - ansible-clickhouse
  post_tasks:
    - name: Wait for Clickhouse
      ansible.builtin.wait_for:
        port: 9000
        delay: 30
- name: Install Vector
  hosts: vector
  roles:
    - vector-role
- name: Install Lighthouse
  hosts: lighthouse
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
  roles:
    - lighthouse-role
  handlers:
    - name: Start Nginx
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
  pre_tasks:
    - name: Install centos dependencies
      become: true
      ansible.builtin.command: amazon-linux-extras install epel -y
      args:
        creates: /etc/yum.repos.d/epel.repo
    - name: Create {{ document_root }}
      become: true
      ansible.builtin.file:
        path: "{{ document_root }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0775
    - name: Create nginx directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0775
      with_items:
        - "/etc/nginx/sites-available/"
        - "/etc/nginx/sites-enabled/"
  post_tasks:
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: "nginx"
      notify: Start Nginx
    - name: Force Service Start
      ansible.builtin.meta: flush_handlers
    - name: Setup Nginx Config
      become: true
      ansible.builtin.template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-available/default"
        mode: 0644
        owner: ec2-user
        group: ec2-user
      notify: Start Nginx
    - name: Enable Nginx Config
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/default"
        dest: "/etc/nginx/sites-enabled/default"
        state: link
      notify: Start Nginx
    - name: Force Service Start
      ansible.builtin.meta: flush_handlers
