---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.systemd:
        name: clickhouse-server.service
        state: started
        enabled: yes
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item.package }}-{{ clickhouse_version }}.{{ item.arch }}.rpm"
            dest: "./{{ item.package }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name: "{{ item.package }}-{{ clickhouse_version }}.rpm"
      with_items: "{{ clickhouse_packages }}"
      notify: Start clickhouse service
    - name: Flush
      meta: flush_handlers
    - name: Wait for Clickhouse
      ansible.builtin.wait_for:
         port: 9000
         delay: 30
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
