---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.systemd:
        name: clickhouse-server.service
        state: started
        enabled: yes
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item.package }}-{{ clickhouse_version }}.{{ item.arch }}.rpm"
            dest: "./{{ item.package }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name: "{{ item.package }}-{{ clickhouse_version }}.rpm"
      with_items: "{{ clickhouse_packages }}"
      notify: Start clickhouse service
    - name: Flush
      meta: flush_handlers
    - name: Wait for Clickhouse
      ansible.builtin.wait_for:
         port: 9000
         delay: 30
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
- name: Install Vector
  hosts: clickhouse
  handlers:
     - name: Start Vector
       become: true
       ansible.builtin.systemd:
           name: vector
           state: restarted
           enabled: true
  tasks:
     - name: Get Vector Distrib
       ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
            dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
     - name: Install Vector package
       become: true
       ansible.builtin.yum:
           name: "vector-{{ vector_version }}-1.x86_64.rpm"
     - name: Copy Service Script
       become: true
       template:
         src: "vector.service.j2"
         dest: "/etc/systemd/system/vector.service"
         mode: 0644
         owner: root
         group: root
     - name: Configure Vector
       become: true
       template:
          src: vector.j2
          dest: "/etc/vector/vector.toml"
          mode: 0644
          owner: ec2-user
          group: ec2-user
       notify: Start Vector
     - name: Flush
       meta: flush_handlers
